//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBlog.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string BannerImage { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> PublishedToDate { get; set; }
        public bool IsArchived { get; set; }
        public int WorkFlowId { get; set; }
        public int UserId { get; set; }
    
        public virtual BlogUser BlogUser { get; set; }
        public virtual WorkFlowStep WorkFlowStep { get; set; }
    }
}
